-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-05-30 15:09:42 CEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE activity_status ( 
   status_id INTEGER NOT NULL, 
   name VARCHAR(255) NOT NULL 
);

ALTER TABLE activity_status 
   ADD CONSTRAINT activity_status_PK PRIMARY KEY ( status_id );

CREATE TABLE aircraft 
    ( 
     aircraft_id         INTEGER  NOT NULL, 
     registration_number VARCHAR(255)  NOT NULL , 
     status_id           INTEGER  NOT NULL , 
     max_seat_capacity   INTEGER  NOT NULL , 
     aircraft_type_id    INTEGER  NOT NULL 
    ) 
;

ALTER TABLE aircraft 
    ADD CONSTRAINT aircraft_PK PRIMARY KEY ( aircraft_id ) ;

CREATE TABLE aircraft_cabin_class 
    ( 
     aircraft_cabin_id INTEGER  NOT NULL, 
     aircraft_id       INTEGER  NOT NULL , 
     cabin_class_id    INTEGER  NOT NULL , 
     seat_capacity     INTEGER 
    ) 
;

ALTER TABLE aircraft_cabin_class 
    ADD CONSTRAINT aircraft_cabin_class_PK PRIMARY KEY ( aircraft_cabin_id ) ;

CREATE TABLE aircraft_manufacturer 
    ( 
     aircraft_manufacturer_id INTEGER  NOT NULL, 
     name                     VARCHAR(255)  NOT NULL 
    ) 
;

ALTER TABLE aircraft_manufacturer 
    ADD CONSTRAINT aircraft_manufacturer_PK PRIMARY KEY ( aircraft_manufacturer_id ) ;

CREATE TABLE aircraft_type 
    ( 
     aircraft_type_id         INTEGER  NOT NULL, 
     model                    VARCHAR(255)  NOT NULL , 
     aircraft_manufacturer_id INTEGER  NOT NULL 
    ) 
;

ALTER TABLE aircraft_type 
    ADD CONSTRAINT aircraft_type_PK PRIMARY KEY ( aircraft_type_id ) ;

CREATE TABLE airport 
    ( 
     airport_id   INTEGER  NOT NULL, 
     name         VARCHAR(255)  NOT NULL , 
     airport_code VARCHAR(10)  NOT NULL , 
     city_id      INTEGER  NOT NULL 
    ) 
;

ALTER TABLE airport 
    ADD CONSTRAINT airport_PK PRIMARY KEY ( airport_id ) ;

CREATE TABLE baggage 
    ( 
     baggage_id      INTEGER  NOT NULL, 
     weight          DECIMAL(5,2)  NOT NULL , 
     extra_fee       DECIMAL(8,2) , 
     baggage_type_id INTEGER  NOT NULL , 
     ticket_id       VARCHAR(50)  NOT NULL 
    ) 
;

ALTER TABLE baggage 
    ADD CONSTRAINT baggage_PK PRIMARY KEY ( baggage_id ) ;

CREATE TABLE baggage_type 
    ( 
     baggage_type_id INTEGER  NOT NULL, 
     name            VARCHAR(255)  NOT NULL 
    ) 
;

ALTER TABLE baggage_type 
    ADD CONSTRAINT baggage_type_PK PRIMARY KEY ( baggage_type_id ) ;

CREATE TABLE boarding_pass 
    ( 
     pass_id       VARCHAR(50)  NOT NULL , 
     boarding_time DATETIME  NOT NULL , 
     gate_number   VARCHAR(20)  NOT NULL , 
     ticket_id     VARCHAR(50)  NOT NULL , 
     seat_id       INTEGER  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX boarding_pass__IDX ON boarding_pass 
    ( 
     ticket_id ASC 
    ) 
;

ALTER TABLE boarding_pass 
    ADD CONSTRAINT boarding_pass_PK PRIMARY KEY ( pass_id ) ;

CREATE TABLE cabin_class 
    ( 
     cabin_class_id INTEGER  NOT NULL, 
     name VARCHAR(255) NOT NULL , 
     seat_pitch     DECIMAL(7,2) , 
     seat_width     DECIMAL(7,2) , 
     seat_layout    VARCHAR(16) 
    ) 
;

ALTER TABLE cabin_class 
    ADD CONSTRAINT cabin_class_PK PRIMARY KEY ( cabin_class_id ) ;

CREATE TABLE city 
    ( 
     city_id    INTEGER  NOT NULL, 
     name       VARCHAR(50)  NOT NULL , 
     country_id INTEGER  NOT NULL 
    ) 
;

ALTER TABLE city 
    ADD CONSTRAINT city_PK PRIMARY KEY ( city_id ) ;

CREATE TABLE client 
    ( 
     client_id     INTEGER  NOT NULL, 
     first_name    VARCHAR(255)  NOT NULL , 
     last_name     VARCHAR(255)  NOT NULL , 
     email_address VARCHAR(255)  NOT NULL 
    ) 
;

ALTER TABLE client 
    ADD CONSTRAINT client_PK PRIMARY KEY ( client_id ) ;

CREATE TABLE country 
    ( 
     country_id INTEGER  NOT NULL, 
     name       VARCHAR(255)  NOT NULL , 
     code       VARCHAR(10)  NOT NULL 
    ) 
;

ALTER TABLE country 
    ADD CONSTRAINT country_PK PRIMARY KEY ( country_id ) ;

ALTER TABLE country 
    ADD CONSTRAINT country_code_UN UNIQUE ( code ) ;

ALTER TABLE country 
    ADD CONSTRAINT country_name_UN UNIQUE ( name ) ;

CREATE TABLE crew_role 
    ( 
     role_id   INTEGER  NOT NULL, 
     role_name VARCHAR(255)  NOT NULL 
    ) 
;

ALTER TABLE crew_role 
    ADD CONSTRAINT crew_role_PK PRIMARY KEY ( role_id ) ;

CREATE TABLE currency 
    ( 
     currency_id INTEGER  NOT NULL, 
     name        VARCHAR(60)  NOT NULL , 
     code        VARCHAR(6)  NOT NULL 
    ) 
;

ALTER TABLE currency 
    ADD CONSTRAINT currency_PK PRIMARY KEY ( currency_id ) ;

ALTER TABLE currency 
    ADD CONSTRAINT currency_code_UN UNIQUE ( code ) ;

CREATE TABLE department 
    ( 
     dept_no VARCHAR(6)  NOT NULL , 
     name    VARCHAR(255)  NOT NULL 
    ) 
;

ALTER TABLE department 
    ADD CONSTRAINT department_PK PRIMARY KEY ( dept_no ) ;

CREATE TABLE document_type 
    ( 
     document_type_id INTEGER  NOT NULL , 
     name             VARCHAR(255)  NOT NULL 
    ) 
;

ALTER TABLE document_type 
    ADD CONSTRAINT document_type_PK PRIMARY KEY ( document_type_id ) ;

CREATE TABLE employee 
    ( 
     employee_id    INTEGER  NOT NULL , 
     first_name     VARCHAR(255)  NOT NULL , 
     last_name      VARCHAR(255)  NOT NULL , 
     other_names    VARCHAR(255) , 
     monthly_salary DECIMAL(16,2)  NOT NULL , 
     date_of_birth  DATETIME  NOT NULL , 
     email_address  VARCHAR(255)  NOT NULL , 
     phone_number   VARCHAR(255)  NOT NULL , 
     hire_date      DATETIME  NOT NULL , 
     gender_id      INTEGER  NOT NULL , 
     nationality_id INTEGER  NOT NULL 
    ) 
;

ALTER TABLE employee 
    ADD CONSTRAINT employee_PK PRIMARY KEY ( employee_id ) ;

CREATE TABLE employee_assignment 
    ( 
     assignment_id   INTEGER  NOT NULL , 
     start_date      DATETIME  NOT NULL , 
     end_date        DATE , 
     employee_id     INTEGER  NOT NULL , 
     job_position_id INTEGER  NOT NULL , 
     dept_no         VARCHAR(6)  NOT NULL 
    ) 
;

ALTER TABLE employee_assignment 
    ADD CONSTRAINT employee_assignment_PK PRIMARY KEY ( assignment_id ) ;

CREATE TABLE flight 
    ( 
     flight_id            INTEGER  NOT NULL, 
     base_departure_time  DATETIME  NOT NULL , 
     base_arrival_time    DATETIME  NOT NULL , 
     departure_airport_id INTEGER  NOT NULL , 
     arrival_airport_id   INTEGER  NOT NULL , 
     aircraft_id          INTEGER  NOT NULL 
    ) 
;

ALTER TABLE flight 
    ADD CONSTRAINT flight_PK PRIMARY KEY ( flight_id ) ;

CREATE TABLE flight_crew 
    ( 
     flight_crew_id INTEGER  NOT NULL, 
     note           VARCHAR(255) , 
     flight_id      INTEGER  NOT NULL , 
     employee_id    INTEGER  NOT NULL , 
     role_id        INTEGER  NOT NULL 
    ) 
;

ALTER TABLE flight_crew 
    ADD CONSTRAINT flight_crew_PK PRIMARY KEY ( flight_crew_id ) ;

CREATE TABLE flight_schedule 
    ( 
     flight_schedule_id   INTEGER  NOT NULL, 
     departure_time       DATETIME  NOT NULL , 
     arrival_time         DATE , 
     schedule_update_time DATE , 
     delay_reason         VARCHAR(255) , 
     flight_id            INTEGER  NOT NULL 
    ) 
;

ALTER TABLE flight_schedule 
    ADD CONSTRAINT flight_schedule_PK PRIMARY KEY ( flight_schedule_id ) ;

CREATE TABLE gender 
    ( 
     gender_id INTEGER  NOT NULL , 
     name      VARCHAR(255)  NOT NULL 
    ) 
;

ALTER TABLE gender 
    ADD CONSTRAINT gender_PK PRIMARY KEY ( gender_id ) ;

CREATE TABLE job_position 
    ( 
     job_position_id INTEGER  NOT NULL, 
     title           VARCHAR(255)  NOT NULL 
    ) 
;

ALTER TABLE job_position 
    ADD CONSTRAINT job_position_PK PRIMARY KEY ( job_position_id ) ;

CREATE TABLE nationality 
    ( 
     nationality_id INTEGER  NOT NULL, 
     name           VARCHAR(50)  NOT NULL 
    ) 
;

ALTER TABLE nationality 
    ADD CONSTRAINT nationality_PK PRIMARY KEY ( nationality_id ) ;

ALTER TABLE nationality 
    ADD CONSTRAINT nationality_name_UN UNIQUE ( name ) ;

CREATE TABLE payment 
    ( 
     payment_id   INTEGER  NOT NULL, 
     amount_paid  DECIMAL(10,2)  NOT NULL , 
     payment_date DATETIME  NOT NULL , 
     method_id    INTEGER  NOT NULL , 
     status_id    INTEGER  NOT NULL , 
     currency_id  INTEGER  NOT NULL , 
     ticket_id    VARCHAR(50)  NOT NULL 
    ) 
;

ALTER TABLE payment 
    ADD CONSTRAINT payment_PK PRIMARY KEY ( payment_id ) ;

CREATE TABLE payment_method 
    ( 
     method_id INTEGER  NOT NULL, 
     name      VARCHAR(255)  NOT NULL 
    ) 
;

ALTER TABLE payment_method 
    ADD CONSTRAINT payment_method_PK PRIMARY KEY ( method_id ) ;

CREATE TABLE payment_status 
    ( 
     status_id INTEGER  NOT NULL, 
     name      VARCHAR(20)  NOT NULL 
    ) 
;

ALTER TABLE payment_status 
    ADD CONSTRAINT payment_status_PK PRIMARY KEY ( status_id ) ;

CREATE TABLE seat 
    ( 
     seat_id           INTEGER  NOT NULL, 
     seat_row          INTEGER  NOT NULL , 
     seat_number       VARCHAR(5)  NOT NULL , 
     type_id           INTEGER  NOT NULL , 
     aircraft_cabin_id INTEGER  NOT NULL 
    ) 
;

ALTER TABLE seat 
    ADD CONSTRAINT seat_PK PRIMARY KEY ( seat_id ) ;

CREATE TABLE seat_type 
    ( 
     type_id INTEGER  NOT NULL, 
     name    VARCHAR(255) NOT NULL 
    ) 
;

ALTER TABLE seat_type 
    ADD CONSTRAINT seat_type_PK PRIMARY KEY ( type_id ) ;

CREATE TABLE ticket 
    ( 
     ticket_id         VARCHAR(50) NOT NULL, 
     booking_time      DATETIME  NOT NULL , 
     price             DECIMAL(10,2)  NOT NULL , 
     pax_first_name    VARCHAR(255)  NOT NULL , 
     pax_last_name     VARCHAR(255)  NOT NULL , 
     pax_date_of_birth DATETIME  NOT NULL , 
     pax_phone_number  VARCHAR(255)  NOT NULL , 
     pax_email_address VARCHAR(255) , 
     flight_id         INTEGER  NOT NULL , 
     client_id         INTEGER  NOT NULL , 
     document_type_id  INTEGER  NOT NULL , 
     currency_id       INTEGER  NOT NULL , 
     seat_id           INTEGER  NOT NULL 
    ) 
;

ALTER TABLE ticket 
    ADD CONSTRAINT ticket_PK PRIMARY KEY ( ticket_id ) ;

ALTER TABLE aircraft 
    ADD CONSTRAINT aircraft_activity_status_FK FOREIGN KEY 
    ( 
     status_id
    ) 
    REFERENCES activity_status 
    ( 
     status_id
    ) 
;

ALTER TABLE aircraft 
    ADD CONSTRAINT aircraft_aircraft_type_FK FOREIGN KEY 
    ( 
     aircraft_type_id
    ) 
    REFERENCES aircraft_type 
    ( 
     aircraft_type_id
    ) 
;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE aircraft_cabin_class 
    ADD CONSTRAINT aircraft_cabin_class_aircraft_FK FOREIGN KEY 
    ( 
     aircraft_id
    ) 
    REFERENCES aircraft 
    ( 
     aircraft_id
    ) 
;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE aircraft_cabin_class 
    ADD CONSTRAINT aircraft_cabin_class_cabin_class_FK FOREIGN KEY 
    ( 
     cabin_class_id
    ) 
    REFERENCES cabin_class 
    ( 
     cabin_class_id
    ) 
;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE aircraft_type 
    ADD CONSTRAINT aircraft_type_aircraft_manufacturer_FK FOREIGN KEY 
    ( 
     aircraft_manufacturer_id
    ) 
    REFERENCES aircraft_manufacturer 
    ( 
     aircraft_manufacturer_id
    ) 
;

ALTER TABLE airport 
    ADD CONSTRAINT airport_city_FK FOREIGN KEY 
    ( 
     city_id
    ) 
    REFERENCES city 
    ( 
     city_id
    ) 
;

ALTER TABLE baggage 
    ADD CONSTRAINT baggage_baggage_type_FK FOREIGN KEY 
    ( 
     baggage_type_id
    ) 
    REFERENCES baggage_type 
    ( 
     baggage_type_id
    ) 
;

ALTER TABLE baggage 
    ADD CONSTRAINT baggage_ticket_FK FOREIGN KEY 
    ( 
     ticket_id
    ) 
    REFERENCES ticket 
    ( 
     ticket_id
    ) 
;

ALTER TABLE boarding_pass 
    ADD CONSTRAINT boarding_pass_seat_FK FOREIGN KEY 
    ( 
     seat_id
    ) 
    REFERENCES seat 
    ( 
     seat_id
    ) 
;

ALTER TABLE boarding_pass 
    ADD CONSTRAINT boarding_pass_ticket_FK FOREIGN KEY 
    ( 
     ticket_id
    ) 
    REFERENCES ticket 
    ( 
     ticket_id
    ) 
;

ALTER TABLE city 
    ADD CONSTRAINT city_country_FK FOREIGN KEY 
    ( 
     country_id
    ) 
    REFERENCES country 
    ( 
     country_id
    ) 
;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE employee_assignment 
    ADD CONSTRAINT employee_assignment_department_FK FOREIGN KEY 
    ( 
     dept_no
    ) 
    REFERENCES department 
    ( 
     dept_no
    ) 
;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE employee_assignment 
    ADD CONSTRAINT employee_assignment_employee_FK FOREIGN KEY 
    ( 
     employee_id
    ) 
    REFERENCES employee 
    ( 
     employee_id
    ) 
;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE employee_assignment 
    ADD CONSTRAINT employee_assignment_job_position_FK FOREIGN KEY 
    ( 
     job_position_id
    ) 
    REFERENCES job_position 
    ( 
     job_position_id
    ) 
;

ALTER TABLE employee 
    ADD CONSTRAINT employee_gender_FK FOREIGN KEY 
    ( 
     gender_id
    ) 
    REFERENCES gender 
    ( 
     gender_id
    ) 
;

ALTER TABLE employee 
    ADD CONSTRAINT employee_nationality_FK FOREIGN KEY 
    ( 
     nationality_id
    ) 
    REFERENCES nationality 
    ( 
     nationality_id
    ) 
;

ALTER TABLE flight 
    ADD CONSTRAINT flight_aircraft_FK FOREIGN KEY 
    ( 
     aircraft_id
    ) 
    REFERENCES aircraft 
    ( 
     aircraft_id
    ) 
;

ALTER TABLE flight 
    ADD CONSTRAINT flight_airport_FK FOREIGN KEY 
    ( 
     arrival_airport_id
    ) 
    REFERENCES airport 
    ( 
     airport_id
    ) 
;

ALTER TABLE flight 
    ADD CONSTRAINT flight_airport_FKv2 FOREIGN KEY 
    ( 
     departure_airport_id
    ) 
    REFERENCES airport 
    ( 
     airport_id
    ) 
;

ALTER TABLE flight_crew 
    ADD CONSTRAINT flight_crew_crew_role_FK FOREIGN KEY 
    ( 
     role_id
    ) 
    REFERENCES crew_role 
    ( 
     role_id
    ) 
;

ALTER TABLE flight_crew 
    ADD CONSTRAINT flight_crew_employee_FK FOREIGN KEY 
    ( 
     employee_id
    ) 
    REFERENCES employee 
    ( 
     employee_id
    ) 
;

ALTER TABLE flight_crew 
    ADD CONSTRAINT flight_crew_flight_FK FOREIGN KEY 
    ( 
     flight_id
    ) 
    REFERENCES flight 
    ( 
     flight_id
    ) 
;

ALTER TABLE flight_schedule 
    ADD CONSTRAINT flight_schedule_flight_FK FOREIGN KEY 
    ( 
     flight_id
    ) 
    REFERENCES flight 
    ( 
     flight_id
    ) 
;

ALTER TABLE payment 
    ADD CONSTRAINT payment_currency_FK FOREIGN KEY 
    ( 
     currency_id
    ) 
    REFERENCES currency 
    ( 
     currency_id
    ) 
;

ALTER TABLE payment 
    ADD CONSTRAINT payment_payment_method_FK FOREIGN KEY 
    ( 
     method_id
    ) 
    REFERENCES payment_method 
    ( 
     method_id
    ) 
;

ALTER TABLE payment 
    ADD CONSTRAINT payment_payment_status_FK FOREIGN KEY 
    ( 
     status_id
    ) 
    REFERENCES payment_status 
    ( 
     status_id
    ) 
;

ALTER TABLE payment 
    ADD CONSTRAINT payment_ticket_FK FOREIGN KEY 
    ( 
     ticket_id
    ) 
    REFERENCES ticket 
    ( 
     ticket_id
    ) 
;

ALTER TABLE seat 
    ADD CONSTRAINT seat_aircraft_cabin_class_FK FOREIGN KEY 
    ( 
     aircraft_cabin_id
    ) 
    REFERENCES aircraft_cabin_class 
    ( 
     aircraft_cabin_id
    ) 
;

ALTER TABLE seat 
    ADD CONSTRAINT seat_seat_type_FK FOREIGN KEY 
    ( 
     type_id
    ) 
    REFERENCES seat_type 
    ( 
     type_id
    ) 
;

ALTER TABLE ticket 
    ADD CONSTRAINT ticket_client_FK FOREIGN KEY 
    ( 
     client_id
    ) 
    REFERENCES client 
    ( 
     client_id
    ) 
;

ALTER TABLE ticket 
    ADD CONSTRAINT ticket_currency_FK FOREIGN KEY 
    ( 
     currency_id
    ) 
    REFERENCES currency 
    ( 
     currency_id
    ) 
;

ALTER TABLE ticket 
    ADD CONSTRAINT ticket_document_type_FK FOREIGN KEY 
    ( 
     document_type_id
    ) 
    REFERENCES document_type 
    ( 
     document_type_id
    ) 
;

ALTER TABLE ticket 
    ADD CONSTRAINT ticket_flight_FK FOREIGN KEY 
    ( 
     flight_id
    ) 
    REFERENCES flight 
    ( 
     flight_id
    ) 
;

ALTER TABLE ticket 
    ADD CONSTRAINT ticket_seat_FK FOREIGN KEY 
    ( 
     seat_id
    ) 
    REFERENCES seat 
    ( 
     seat_id
    ) 
;


ALTER TABLE activity_status 
MODIFY status_id INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE flight 
MODIFY flight_id INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE aircraft 
MODIFY aircraft_id INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE airport 
MODIFY airport_id INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE aircraft_type 
MODIFY aircraft_type_id INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE aircraft_manufacturer 
MODIFY aircraft_manufacturer_id INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE city 
MODIFY city_id INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE country 
MODIFY country_id INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE client 
MODIFY client_id INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE employee 
MODIFY employee_id INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE crew_role 
MODIFY role_id INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE seat 
MODIFY seat_id INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE cabin_class 
MODIFY cabin_class_id INTEGER NOT NULL AUTO_INCREMENT;


ALTER TABLE aircraft_cabin_class 
MODIFY aircraft_cabin_id INTEGER NOT NULL AUTO_INCREMENT;


ALTER TABLE seat_type 
MODIFY type_id INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE baggage_type 
MODIFY baggage_type_id INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE payment 
MODIFY payment_id INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE payment_method 
MODIFY method_id INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE payment_status 
MODIFY status_id INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE currency 
MODIFY currency_id INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE document_type 
MODIFY document_type_id INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE employee_assignment 
MODIFY assignment_id INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE gender 
MODIFY gender_id INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE nationality 
MODIFY nationality_id INTEGER NOT NULL AUTO_INCREMENT;


ALTER TABLE flight_crew 
MODIFY flight_crew_id INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE flight_schedule 
MODIFY flight_schedule_id INTEGER NOT NULL AUTO_INCREMENT;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            31
-- CREATE INDEX                             1
-- ALTER TABLE                             69
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   8
-- WARNINGS                                 0
